name: CI

on:
  push:
  pull_request:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  GTEST_REF: b85864c64758dec007208e56af933fc3f52044ee

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.24.x'
    - name: Test cmake version
      run: cmake --version
    
    - name: Set relative paths
      run: | 
        GTEST=$GITHUB_WORKSPACE/googletest
        echo "GTEST=$GTEST" >> $GITHUB_ENV
        SSCDIR=$GITHUB_WORKSPACE/ssc
        echo "SSCDIR=$SSCDIR" >> $GITHUB_ENV
    
    - name: Checkout SSC
      uses: actions/checkout@v4
      with:
         path: ssc

    - name: Test
      # Turn off fast fail for when the landbosse tests write to cerr
      shell: bash
      run: |
        set -e
        # ${SSCDIR}/build/test/Test --gtest_filter="*WakeModel*" > ${SSCDIR}/build/test/gtest.log
        pip install pandas requests
        python ${SSCDIR}/test/compare_elapsed_time.py gtest_log ${SSCDIR}/test/gtest.log
    
    - name: Upload Test Times CSV
      uses: actions/upload-artifact@v4
      with:
          name: SSC Linux Test Time Elapsed
          path: |
            ${{env.SSCDIR}}/test/gtest_elapsed_times.csv
      
  build-on-mac:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.24.x'
    - name: Test cmake version
      run: cmake --version
    
    - name: Set relative paths
      run: | 
        GTEST=$GITHUB_WORKSPACE/googletest
        echo "GTEST=$GTEST" >> $GITHUB_ENV
        SSCDIR=$GITHUB_WORKSPACE/ssc
        echo "SSCDIR=$SSCDIR" >> $GITHUB_ENV
    
    - name: Checkout SSC
      uses: actions/checkout@v4
      with:
         path: ssc

    - name: Test
      # Turn off fast fail for when the landbosse tests write to cerr
      run: |
        set -e
        # ${SSCDIR}/build/test/Test --gtest_filter="*WakeModel*" > ${SSCDIR}/build/test/gtest.log
        pip install pandas requests
        python ${SSCDIR}/test/compare_elapsed_time.py gtest_log ${SSCDIR}/test/gtest.log
      shell: bash      

    - name: Upload Test Times CSV
      if: ${{ matrix.os == 'macos-latest' }}
      uses: actions/upload-artifact@v4
      with:
          name: SSC Mac Arm Test Time Elapsed
          path: |
            ${{env.SSCDIR}}/test/gtest_elapsed_times.csv 

    - name: Upload Test Times CSV
      if: ${{ matrix.os != 'macos-latest' }}
      uses: actions/upload-artifact@v4
      with:
          name: SSC Mac Intel Test Time Elapsed
          path: |
            ${{env.SSCDIR}}/test/gtest_elapsed_times.csv 

  build-on-windows:
    runs-on: windows-2019

    steps:
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.24.x'
    - name: Test cmake version
      run: cmake --version
    
    - name: Set relative paths
      shell: bash
      run: | 
        GTEST=$GITHUB_WORKSPACE/googletest
        echo "GTEST=$GTEST" >> $GITHUB_ENV
        SSCDIR=$GITHUB_WORKSPACE/ssc
        echo "SSCDIR=$SSCDIR" >> $GITHUB_ENV
    
    
    - name: Checkout SSC
      uses: actions/checkout@v4
      with:
          path: ssc    

    - name: Test
      shell: bash
      # Turn off fast fail for when the landbosse tests write to cerr
      run: |
        # cd ${SSCDIR}/build/test/Release
        # ./Test.exe --gtest_filter="*WakeModel*" > ${SSCDIR}/build/test/gtest.log
        pip install pandas requests
        python ${SSCDIR}/test/compare_elapsed_time.py gtest_log ${SSCDIR}/test/gtest.log
  
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
          name: SSC Windows Test Times CSV
          path: |
            ${{env.SSCDIR}}\test\gtest_elapsed_times.csv

