name: Update Elapsed Test Times

on:
  # release:
    # types: [published]
  push

env:
    GITHUB_SHA: d69ac43306dff5a61b5798d280ee68fd8fbd4e3d

jobs:
  update_elapsed_test_times:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, ubuntu-latest, macos-14-large, macos-latest]
      fail-fast: false

    steps:
    - name: Get Release SHA
      run: |
        echo $GITHUB_SHA

    - name: Checkout SSC
      uses: actions/checkout@v4
      with:
          path: ssc

    - name: Create SSC branch
      shell: bash
      run: | 
        cd ${{ github.workspace }}/ssc
        git checkout -b update_test_times

    - name: Download Release Test Times
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      shell: bash
      run: |
        pip install pandas requests
        python '${{ github.workspace }}/ssc/test/compare_elapsed_time.py' download_csv $GITHUB_SHA '${{ github.workspace }}/ssc/test/elapsed_time_release'

    - name: create pull request
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git add '${{ github.workspace }}/ssc/test/elapsed_time_release'
        git commit -m "Update elapsed_time_release for ${{ matrix.os }}"
        gh pr create -B develop -H update_test_times --title 'Merge update_test_times into develop' --body 'Created by Github action'